### ISSUE TITLE
Hot to run tasmotahab from console on macos?

### ISSUE THREAD

**Issue by Trickx** [Gifford47/tasmohab#4]
This project looks very interesting!
Unfortunately I can't get it to work.

My System:
`macOS Montery`
Python:
`Python 3.8.2 (default, Oct  2 2020, 10:45:42) 
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
`

After installation of the dependencies, execution of
`python3 tasmohabUI.py`
results in the GUI to be started, but it does not do anything.
I tried to discover a tasmota device via http without success.
<img width="1186" alt="Bildschirmfoto 2022-11-08 um 19 43 21" src="https://user-images.githubusercontent.com/8447808/200649326-88d54f66-0f5b-4c69-9751-f16b0e750e2a.png">

Trying to run
`python3 tasmohab.py`
leads to a crash:

```
sven@iMac tasmohab % python3 tasmohab.py
objc[90940]: Class QMacAutoReleasePoolTracker is implemented in both /Users/sven/Library/Python/3.8/lib/python/site-packages/PyQt6/Qt6/lib/QtCore.framework/Versions/A/QtCore (0x10d29d940) and /Library/Python/3.8/site-packages/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore (0x111841198). One of the two will be used. Which one is undefined.
objc[90940]: Class QT_ROOT_LEVEL_POOL__THESE_OBJECTS_WILL_BE_RELEASED_WHEN_QAPP_GOES_OUT_OF_SCOPE is implemented in both /Users/sven/Library/Python/3.8/lib/python/site-packages/PyQt6/Qt6/lib/QtCore.framework/Versions/A/QtCore (0x10d29d9b8) and /Library/Python/3.8/site-packages/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore (0x111841210). One of the two will be used. Which one is undefined.
objc[90940]: Class KeyValueObserver is implemented in both /Users/sven/Library/Python/3.8/lib/python/site-packages/PyQt6/Qt6/lib/QtCore.framework/Versions/A/QtCore (0x10d29d9e0) and /Library/Python/3.8/site-packages/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore (0x111841238). One of the two will be used. Which one is undefined.
objc[90940]: Class RunLoopModeTracker is implemented in both /Users/sven/Library/Python/3.8/lib/python/site-packages/PyQt6/Qt6/lib/QtCore.framework/Versions/A/QtCore (0x10d29da30) and /Library/Python/3.8/site-packages/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore (0x111841288). One of the two will be used. Which one is undefined.
Running threads:
MainThread
UI_Thread


WARNING: QApplication was not created in the main() thread.
qt.qpa.drawing: Layer-backing is always enabled.  QT_MAC_WANTS_LAYER/_q_mac_wantsLayer has no effect.
2022-11-08 19:46:55.624 Python[90940:1972387] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff81d9d0773 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff81d730bc3 objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff81d9f9056 -[NSException raise] + 9
	3   AppKit                              0x00007ff8203b50a4 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 321
	4   AppKit                              0x00007ff8203a1054 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1288
	5   AppKit                              0x00007ff8203a0b46 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
	6   AppKit                              0x00007ff820681aa7 -[NSWindow initWithContentRect:styleMask:backing:defer:screen:] + 50
	7   libqcocoa.dylib                     0x0000000110c8a2be _ZN20QCocoaSystemTrayIcon17statusItemClickedEv + 232222
	8   libqcocoa.dylib                     0x0000000110c60948 _ZN20QCocoaSystemTrayIcon17statusItemClickedEv + 61864
	9   libqcocoa.dylib                     0x0000000110c597a3 _ZN20QCocoaSystemTrayIcon17statusItemClickedEv + 32771
	10  libqcocoa.dylib                     0x0000000110c5923c _ZN20QCocoaSystemTrayIcon17statusItemClickedEv + 31388
	11  QtGui                               0x000000010f8efd8e _ZN14QWindowPrivate6createEby + 206
	12  QtWidgets                           0x0000000110655f38 _ZN14QWidgetPrivate6createEv + 1096
	13  QtWidgets                           0x0000000110653940 _ZN7QWidget6createEybb + 320
	14  QtWidgets                           0x00000001107ec407 _ZNK8QMenuBar15initStyleOptionEP20QStyleOptionMenuItemPK7QAction + 1783
	15  QtWidgets                           0x00000001107ebf85 _ZNK8QMenuBar15initStyleOptionEP20QStyleOptionMenuItemPK7QAction + 629
	16  QtWidgets.abi3.so                   0x000000010f0cf664 _ZL18init_type_QMenuBarP17_sipSimpleWrapperP7_objectS2_PS2_S3_S3_ + 116
	17  sip.cpython-38-darwin.so            0x000000010c3e7ae9 sipSimpleWrapper_init + 505
	18  Python3                             0x000000010babc054 type_call + 292
	19  Python3                             0x000000010ba66dd6 _PyObject_MakeTpCall + 374
	20  Python3                             0x000000010bb4713c call_function + 652
	21  Python3                             0x000000010bb436d6 _PyEval_EvalFrameDefault + 29782
	22  Python3                             0x000000010ba6778d function_code_fastcall + 237
	23  Python3                             0x000000010ba6a14b method_vectorcall + 171
	24  Python3                             0x000000010bb47012 call_function + 354
	25  Python3                             0x000000010bb436d6 _PyEval_EvalFrameDefault + 29782
	26  Python3                             0x000000010bb48097 _PyEval_EvalCodeWithName + 3287
	27  Python3                             0x000000010ba6790d _PyFunction_Vectorcall + 253
	28  Python3                             0x000000010ba66c0a _PyObject_FastCallDict + 218
	29  Python3                             0x000000010ba682f3 _PyObject_Call_Prepend + 131
	30  Python3                             0x000000010bac0b74 slot_tp_init + 180
	31  Python3                             0x000000010babc054 type_call + 292
	32  Python3                             0x000000010ba66dd6 _PyObject_MakeTpCall + 374
	33  Python3                             0x000000010bb4713c call_function + 652
	34  Python3                             0x000000010bb4378a _PyEval_EvalFrameDefault + 29962
	35  Python3                             0x000000010ba6778d function_code_fastcall + 237
	36  Python3                             0x000000010ba67124 PyVectorcall_Call + 100
	37  Python3                             0x000000010bb43a34 _PyEval_EvalFrameDefault + 30644
	38  Python3                             0x000000010ba6778d function_code_fastcall + 237
	39  Python3                             0x000000010bb47012 call_function + 354
	40  Python3                             0x000000010bb436b9 _PyEval_EvalFrameDefault + 29753
	41  Python3                             0x000000010ba6778d function_code_fastcall + 237
	42  Python3                             0x000000010bb47012 call_function + 354
	43  Python3                             0x000000010bb436b9 _PyEval_EvalFrameDefault + 29753
	44  Python3                             0x000000010ba6778d function_code_fastcall + 237
	45  Python3                             0x000000010ba6a1e2 method_vectorcall + 322
	46  Python3                             0x000000010ba67124 PyVectorcall_Call + 100
	47  Python3                             0x000000010bbe900a t_bootstrap + 74
	48  Python3                             0x000000010bb9a829 pythread_wrapper + 25
	49  libsystem_pthread.dylib             0x00007ff81d88e4e1 _pthread_start + 125
	50  libsystem_pthread.dylib             0x00007ff81d889f6b thread_start + 15
)
libc++abi: terminating with uncaught exception of type NSException
zsh: abort      python3 tasmohab.py
```

**Comment by Gifford47** [comment]
Hi!
I must admit that I can't test the error due to missing macOS. But please test again with Python 3.11 or higher and report the results.

**Comment by Trickx** [comment]
Hi!
well a fresh installation of python3.11 and installing the dependencies from requirements.txt results in the following stack trace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/dirtyjson/attributed_containers.py", line 7, in <module>
    from collections import MutableMapping as DictMixin
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/local/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/collections/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sven/Documents/Projekte/tasmohab/tasmohab.py", line 13, in <module>
    import dirtyjson
  File "/usr/local/lib/python3.11/site-packages/dirtyjson/__init__.py", line 3, in <module>
    from .loader import DirtyJSONLoader
  File "/usr/local/lib/python3.11/site-packages/dirtyjson/loader.py", line 8, in <module>
    from dirtyjson.attributed_containers import AttributedDict, AttributedList
  File "/usr/local/lib/python3.11/site-packages/dirtyjson/attributed_containers.py", line 11, in <module>
    from UserDict import DictMixin
ModuleNotFoundError: No module named 'UserDict'
```

**Comment by Gifford47** [comment]
Ok, there's an issue with python>3.9 and dirtyjson.

A pushed a notice to the developer of dirtyjson. So it should be updated in the next time at pypi.org. After that it should be run out of the box.

Until then please try to run it with python 3.9.x.

Best regards
